### PR TITLE
RPC: removed restrictions for get info in --restricted-rpc

### PR DESCRIPTION
**Pull request by ArqTras**
Removed some restrictions for rpc calls on --public --restricted-rpc node to get more info without harm privacy

### CODE REVIEW

**Comment by ArqTras** [comment]
Temporary disabled node version check untill its finished to prevent ban

**Comment by ArqTras** [comment]
Temporary disabled node version check untill its finished

**Comment by ArqTras** [comment]
more info
It will allow to get more information from public restricted nodes like this local ( started as restricted rpc)

**Review by malbit — CHANGES_REQUESTED** [review]
why did you include changes already made at #290 ??
and AGAIN -> rebase pls

**Comment by ArqTras** [comment]
Updated in to #294

**Pull request closed without merging**
