### PR TITLE
[WIP] Service_Nodes

### PR DESCRIPTION
**Pull request by malbit**
under heavy development

### CODE REVIEW

**Comment by malbit** [comment]
### require #298

**Comment by ArqTras** [comment]
> require #298

Merged

**Review by ArqTras — DISMISSED** [review]
Add checkpoints to new public stagenet network and allow sync without —fixed diff would be good idea

**Comment by ArqTras** [comment]
Just a reminder
```crypto::hash base_id = pbc->get_block_id_by_height(height - 31337);```

**Comment by ArqTras** [comment]
rpc call for register SN needed :)

**Comment by BigslimVdub** [comment]
OS X now building binaries with latest commit. Looks like windows needs update now.

**Review by ArqTras — DISMISSED** [review]

**Review by ArqTras — DISMISSED** [review]

**Review by ArqTras — APPROVED** [review]

**Pull request merged**
