### PR TITLE
Update socks.cpp

### PR DESCRIPTION
**Pull request by ArqTras**

### CODE REVIEW

**Comment by ArqTras** [comment]
Test with PR109, PR117 and PR-118 seems to be correct
Compilation with msys should be corrected

**Comment by malbit** [comment]
I was gonna include that fix at PR #109 :)
If you did it now it is fine for me then

**Comment by malbit** [comment]
> Test with PR109, PR117 and PR-118 seems to be correct
> Compilation with msys should be corrected

What about SetLockPagesPrivilege with PR #109 merged locally ?
Did you get successful compilation under Msys?

**Comment by ArqTras** [comment]
> 
> 
> > Test with PR109, PR117 and PR-118 seems to be correct
> > Compilation with msys should be corrected
> 
> What about SetLockPagesPrivilege with PR #109 merged locally ?
> Did you get successful compilation under Msys?

I need re compile step by step, msys and depends not work for me yet.

**Review by malbit — APPROVED** [review]

**Pull request merged**
